# project-1

19178@DESKTOP-CD6E9HI MINGW64 ~
$ ssh-keygen
Generating public/private rsa key pair.
Enter file in which to save the key (/c/Users/19178/.ssh/id_rsa):
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in /c/Users/19178/.ssh/id_rsa
Your public key has been saved in /c/Users/19178/.ssh/id_rsa.pub
The key fingerprint is:
SHA256:U1znXYfF75/1q5LnJsQj4QwfvksFHwXafOC2KEDPxV4 19178@DESKTOP-CD6E9HI
The key's randomart image is:
+---[RSA 3072]----+
|     .  .. oo..++|
|    . o .o=Eoo..+|
|     . o.o+* .. o|
|      .. == +   .|
|       .S.++   . |
|        .B.+    o|
|         .+ o   =|
|        .. + o .o|
|         .. *o...|
+----[SHA256]-----+

19178@DESKTOP-CD6E9HI MINGW64 ~
$ cat ~/.ssh/id_rsa.pub
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFNrhbwFdKH7bE1ZApJpDGB/2/A99OPGHQtpBLtc2fn2mRn2icnw14RJBaquwvB5u3MuXEmp3DCK4aAfp+e7E4dnGq4T8sY5PV4MMNReKmyAOHyH3ZyDbQF+7CztkuiyX8A5v0TAOmS5AU85Q3JvhCRCjPtsC+TNKDJvtPUZYd514fMn/maO4r2AkRqNfPOJBEmlJsMY1Bm2DXYawVeG59jbX9YhEOn9EY52AJDLVlxx+nobpP4xh/mWWH+zJDZfw8oXRfa0shA4wRkS2wbMlFgxhRxIlxWhyRmXcNgJdABQxJDfpBtMzqu4PF9WZ7g+wQy+JAR+bw5nwPLsPMuiE8h/vHaJUp8GFsCm4+ofsry3qqZ+Ip1/qiN/FVnBaFR2fkTMTq2vqdtYElzoNZzUf0nwg+CMIgNu1aCW0lVrQvhztA28J+HkuVx8hVB8pRvrRmwj/c2J183wdtO7+jLJnQUkCjdGCCYASYQC4BIPmF2Uey9PgBLeFCd/QhqUaFrjc= 19178@DESKTOP-CD6E9HI

19178@DESKTOP-CD6E9HI MINGW64 ~
$ ssh admin-azadmin@VM-173.52.52.5
ssh: Could not resolve hostname vm-173.52.52.5: Name or service not known

19178@DESKTOP-CD6E9HI MINGW64 ~
$ ssh admin@VM-173.52.52.5
ssh: Could not resolve hostname vm-173.52.52.5: Name or service not known

19178@DESKTOP-CD6E9HI MINGW64 ~
$ ssh admin@VM-173.52.52.5
ssh: Could not resolve hostname vm-173.52.52.5: Name or service not known

19178@DESKTOP-CD6E9HI MINGW64 ~
$

19178@DESKTOP-CD6E9HI MINGW64 ~
$ $ ssh admin@VM-173.52.52.5
bash: $: command not found

19178@DESKTOP-CD6E9HI MINGW64 ~
$ ssh admin-username@VM-public-IP
ssh: Could not resolve hostname vm-public-ip: Name or service not known

19178@DESKTOP-CD6E9HI MINGW64 ~
$ $ ssh admin-azureuser@VM-173.52.52.5
bash: $: command not found

19178@DESKTOP-CD6E9HI MINGW64 ~
$ $ ssh admin-azureuser@VM-173.52.52.5
bash: $: command not found

19178@DESKTOP-CD6E9HI MINGW64 ~
$ ssh azureuser@20.98.128.246
ssh: connect to host 20.98.128.246 port 22: Connection timed out

19178@DESKTOP-CD6E9HI MINGW64 ~
$ ssh azureuser@20.98.128.246
The authenticity of host '20.98.128.246 (20.98.128.246)' can't be established.
ED25519 key fingerprint is SHA256:yk8h6ae24qUU3gQFigoVJIm51UoB4sMDTxgoQ6/N4A8.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '20.98.128.246' (ED25519) to the list of known hosts.
Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1055-azure x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Sat Jul 24 03:49:29 UTC 2021

  System load:  0.0               Processes:           108
  Usage of /:   4.7% of 28.90GB   Users logged in:     0
  Memory usage: 20%               IP address for eth0: 10.0.0.4
  Swap usage:   0%

0 updates can be applied immediately.



The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

azureuser@Jump-Box-Provisioner:~$ sudo -l
Matching Defaults entries for azureuser on Jump-Box-Provisioner:
    env_reset, mail_badpass,
    secure_path=/usr/local/sbin\:/usr/local/bin\:/usr/sbin\:/usr/bin\:/sbin\:/bin\:/snap/bin

User azureuser may run the following commands on Jump-Box-Provisioner:
    (ALL : ALL) ALL
    (ALL) NOPASSWD: ALL
azureuser@Jump-Box-Provisioner:~$ sudo apt install docker.io
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package docker.io
E: Couldn't find any package by glob 'docker.io'
E: Couldn't find any package by regex 'docker.io'
azureuser@Jump-Box-Provisioner:~$ sudo apt update
Hit:1 http://azure.archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://azure.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://azure.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:5 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [8570 kB]
Get:6 http://azure.archive.ubuntu.com/ubuntu bionic/universe Translation-en [4941 kB]
Get:7 http://azure.archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [151 kB]
Get:8 http://azure.archive.ubuntu.com/ubuntu bionic/multiverse Translation-en [108 kB]
Get:9 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [2160 kB]
Get:10 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1740 kB]
Get:11 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe Translation-en [372 kB]
Get:12 http://azure.archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [30.5 kB]
Get:13 http://azure.archive.ubuntu.com/ubuntu bionic-updates/multiverse Translation-en [7120 B]
Get:14 http://azure.archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [10.0 kB]
Get:15 http://azure.archive.ubuntu.com/ubuntu bionic-backports/main Translation-en [4764 B]
Get:16 http://azure.archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [10.3 kB]
Get:17 http://azure.archive.ubuntu.com/ubuntu bionic-backports/universe Translation-en [4588 B]
Get:18 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [1813 kB]
Get:19 http://security.ubuntu.com/ubuntu bionic-security/main Translation-en [333 kB]
Get:20 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1132 kB]
Get:21 http://security.ubuntu.com/ubuntu bionic-security/universe Translation-en [257 kB]
Get:22 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [24.8 kB]
Get:23 http://security.ubuntu.com/ubuntu bionic-security/multiverse Translation-en [5072 B]
Fetched 21.9 MB in 4s (4891 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
10 packages can be upgraded. Run 'apt list --upgradable' to see them.
azureuser@Jump-Box-Provisioner:~$ sudo apt install docker.io
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  linux-headers-4.15.0-151
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  bridge-utils containerd pigz runc ubuntu-fan
Suggested packages:
  ifupdown aufs-tools cgroupfs-mount | cgroup-lite debootstrap docker-doc
  rinse zfs-fuse | zfsutils
The following NEW packages will be installed:
  bridge-utils containerd docker.io pigz runc ubuntu-fan
0 upgraded, 6 newly installed, 0 to remove and 10 not upgraded.
Need to get 74.0 MB of archives.
After this operation, 359 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 pigz amd64 2.4-1 [57.4 kB]
Get:2 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 bridge-utils amd64 1.5-15ubuntu1 [30.1 kB]
Get:3 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 runc amd64 1.0.0~rc95-0ubuntu1~18.04.1 [4087 kB]
Get:4 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 containerd amd64 1.5.2-0ubuntu1~18.04.2 [32.9 MB]
Get:5 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 docker.io amd64 20.10.2-0ubuntu1~18.04.2 [36.9 MB]
Get:6 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 ubuntu-fan all 0.12.10 [34.7 kB]
Fetched 74.0 MB in 2s (46.8 MB/s)
Preconfiguring packages ...
Selecting previously unselected package pigz.
(Reading database ... 76951 files and directories currently installed.)
Preparing to unpack .../0-pigz_2.4-1_amd64.deb ...
Unpacking pigz (2.4-1) ...
Selecting previously unselected package bridge-utils.
Preparing to unpack .../1-bridge-utils_1.5-15ubuntu1_amd64.deb ...
Unpacking bridge-utils (1.5-15ubuntu1) ...
Selecting previously unselected package runc.
Preparing to unpack .../2-runc_1.0.0~rc95-0ubuntu1~18.04.1_amd64.deb ...
Unpacking runc (1.0.0~rc95-0ubuntu1~18.04.1) ...
Selecting previously unselected package containerd.
Preparing to unpack .../3-containerd_1.5.2-0ubuntu1~18.04.2_amd64.deb ...
Unpacking containerd (1.5.2-0ubuntu1~18.04.2) ...
Selecting previously unselected package docker.io.
Preparing to unpack .../4-docker.io_20.10.2-0ubuntu1~18.04.2_amd64.deb ...
Unpacking docker.io (20.10.2-0ubuntu1~18.04.2) ...
Selecting previously unselected package ubuntu-fan.
Preparing to unpack .../5-ubuntu-fan_0.12.10_all.deb ...
Unpacking ubuntu-fan (0.12.10) ...
Setting up runc (1.0.0~rc95-0ubuntu1~18.04.1) ...
Setting up containerd (1.5.2-0ubuntu1~18.04.2) ...
Created symlink /etc/systemd/system/multi-user.target.wants/containerd.service → /lib/systemd/system/containerd.service.
Setting up bridge-utils (1.5-15ubuntu1) ...
Setting up ubuntu-fan (0.12.10) ...
Created symlink /etc/systemd/system/multi-user.target.wants/ubuntu-fan.service → /lib/systemd/system/ubuntu-fan.service.
Setting up pigz (2.4-1) ...
Setting up docker.io (20.10.2-0ubuntu1~18.04.2) ...
Adding group `docker' (GID 116) ...
Done.
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /lib/systemd/system/docker.service.
Created symlink /etc/systemd/system/sockets.target.wants/docker.socket → /lib/systemd/system/docker.socket.
Processing triggers for systemd (237-3ubuntu10.49) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for ureadahead (0.100.0-21) ...
azureuser@Jump-Box-Provisioner:~$ sudo systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: e
   Active: active (running) since Sat 2021-07-24 03:54:38 UTC; 41s ago
     Docs: https://docs.docker.com
 Main PID: 3153 (dockerd)
    Tasks: 8
   CGroup: /system.slice/docker.service
           └─3153 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/contain

Jul 24 03:54:38 Jump-Box-Provisioner dockerd[3153]: time="2021-07-24T03:54:38.04
Jul 24 03:54:38 Jump-Box-Provisioner dockerd[3153]: time="2021-07-24T03:54:38.04
Jul 24 03:54:38 Jump-Box-Provisioner dockerd[3153]: time="2021-07-24T03:54:38.04
Jul 24 03:54:38 Jump-Box-Provisioner dockerd[3153]: time="2021-07-24T03:54:38.24
Jul 24 03:54:38 Jump-Box-Provisioner dockerd[3153]: time="2021-07-24T03:54:38.32
Jul 24 03:54:38 Jump-Box-Provisioner dockerd[3153]: time="2021-07-24T03:54:38.51
Jul 24 03:54:38 Jump-Box-Provisioner dockerd[3153]: time="2021-07-24T03:54:38.51
Jul 24 03:54:38 Jump-Box-Provisioner dockerd[3153]: time="2021-07-24T03:54:38.51
Jul 24 03:54:38 Jump-Box-Provisioner systemd[1]: Started Docker Application Cont
Jul 24 03:54:38 Jump-Box-Provisioner dockerd[3153]: time="2021-07-24T03:54:38.59
lines 1-19/19 (END)
[1]+  Stopped                 sudo systemctl status docker
sudo
sudo
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user]
            [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
            prompt] [-T timeout] [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
            prompt] [-T timeout] [-u user] file ...
azureuser@Jump-Box-Provisioner:~$ sudo docker pull cyberxsecurity/ansible
Using default tag: latest
latest: Pulling from cyberxsecurity/ansible
345e3491a907: Pull complete
57671312ef6f: Pull complete
5e9250ddb7d0: Pull complete
06c2579b8983: Pull complete
Digest: sha256:1e59530cfc0fb86b8fefdc2c7b0666e053c9f53a339639fb34e99ffee9812730
Status: Downloaded newer image for cyberxsecurity/ansible:latest
docker.io/cyberxsecurity/ansible:latest
azureuser@Jump-Box-Provisioner:~$ docker run -ti cyberxsecurity/ansible:latest bash
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
azureuser@Jump-Box-Provisioner:~$ sudo su
root@Jump-Box-Provisioner:/home/azureuser# docker run -ti cyberxsecurity/ansible:latest bash
root@f2d3cf099775:~# docker images
bash: docker: command not found
root@f2d3cf099775:~# exit
exit
root@Jump-Box-Provisioner:/home/azureuser# docker images
REPOSITORY               TAG       IMAGE ID       CREATED       SIZE
cyberxsecurity/ansible   latest    7d2d9fa20ccf   8 weeks ago   754MB
root@Jump-Box-Provisioner:/home/azureuser# docker run -it cyberxsecurity/ansible /bin/bash
root@736da561d420:~# ssh-keygen
Generating public/private rsa key pair.
Enter file in which to save the key (/root/.ssh/id_rsa):
Created directory '/root/.ssh'.
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in /root/.ssh/id_rsa
Your public key has been saved in /root/.ssh/id_rsa.pub
The key fingerprint is:
SHA256:Ja/bNcjctiHtwtftyXTUf66H0ASt1KL4DCsbyAOp9ZQ root@736da561d420
The key's randomart image is:
+---[RSA 3072]----+
|             o   |
|            + o  |
|   . .  ...o +   |
|  + E   o+. . . .|
| o = .  S=.  o  o|
|.   = o .+o+. ...|
|     . +..= Bo ++|
|      .  oo=.+=.*|
|        . .oo .*o|
+----[SHA256]-----+
root@736da561d420:~# ls .ssh/
id_rsa  id_rsa.pub
root@736da561d420:~# cat .ssh/id_rsa.pub
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDTL84ehIFnIPcx0OgjNaFt5mYFJalhX74KUyIZsOsijBiVjcX9g06VqBAlw4c/ZSYvuxMkrhp7KCQwLESby4qgFoL+yUYyxWeV+QETJPkIWatZ/0Tv/w1B38E0x5p7Cfy2kye0gA5UwDvLXB/him9wyU/SwTC6QZtbn26nbdgsUEShNcdzJtB6p5/QL1Ut6oKEo2O5aJRTBdYw/tuYqFnBl3pE01cXCnUqL3a1rz22PxHBdK8qvq+gWaaZcAvkTuicyB1JM0b/I0pkZziC/pKDmvbSAnob/6mIvJD7NNlsT4QEsyyIKkPDRTVRv4R17RGXvWKsKg14B2p2bz1iTc2guKvmQeYBxj+SDVq5hDEVMbOJzgLFFtpFBXYbb2ddzWzfXw/7R3xZ34Z0vJXZqn7W/A0COUbH157YY13sKfOjzKuY9uuvaHuMu3sbu5gmd2+8Gv5KdDDyqE/xun+miqTM2xi3dBBI3TdsR1+BcySRHQ4VUvYknW6xd/VyaMTYLT8= root@736da561d420
root@736da561d420:~# ping 10.0.0.5
PING 10.0.0.5 (10.0.0.5) 56(84) bytes of data.
^C
--- 10.0.0.5 ping statistics ---
25 packets transmitted, 0 received, 100% packet loss, time 24572ms

root@736da561d420:~# ssh azureuser@10.0.0.5
The authenticity of host '10.0.0.5 (10.0.0.5)' can't be established.
ECDSA key fingerprint is SHA256:YCs/UdjwHXl6A61I9hnCyPFhxYxKSXPqztVQ7wLI3lo.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '10.0.0.5' (ECDSA) to the list of known hosts.
azureuser@10.0.0.5: Permission denied (publickey).
root@736da561d420:~# ssh azureuser@10.0.0.6
The authenticity of host '10.0.0.6 (10.0.0.6)' can't be established.
ECDSA key fingerprint is SHA256:lGCvuXR1VEfgoXTC/UHQ10jDHfGJ6j5v9ruf7UjAq8o.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '10.0.0.6' (ECDSA) to the list of known hosts.
azureuser@10.0.0.6: Permission denied (publickey).
root@736da561d420:~# ssh azureuser@10.0.0.5
azureuser@10.0.0.5: Permission denied (publickey).
root@736da561d420:~# ls /etc/ansible/
ansible.cfg  hosts
root@736da561d420:~# nano /etc/ansible/hosts
root@736da561d420:~# nano /etc/ansible/ansible.cfg
root@736da561d420:~#
root@736da561d420:~#
root@736da561d420:~# ansible_python_interpreter=/usr/bin/python3
root@736da561d420:~# ls
root@736da561d420:~# ls
root@736da561d420:~# ls /etc/ansible
ansible.cfg  hosts
root@736da561d420:~# ls /etc/ansible/
ansible.cfg  hosts
root@736da561d420:~# nano /etc/ansible/ansible.cfg
root@736da561d420:~# nano /etc/ansible/hosts
root@736da561d420:~# ansible webservers -m ping
10.0.0.5 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: sysadmin@10.0.0.5: Permission denied (publickey).",
    "unreachable": true
}
10.0.0.6 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: sysadmin@10.0.0.6: Permission denied (publickey).",
    "unreachable": true
}
root@736da561d420:~# nano /etc/ansible/hosts
root@736da561d420:~# ansible webservers -m ping
10.0.0.5 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: sysadmin@10.0.0.5: Permission denied (publickey).",
    "unreachable": true
}
10.0.0.6 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: sysadmin@10.0.0.6: Permission denied (publickey).",
    "unreachable": true
}
root@736da561d420:~# nano /etc/ansible/hosts
root@736da561d420:~# ansible webservers -m ping
10.0.0.5 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: sysadmin@10.0.0.5: Permission denied (publickey).",
    "unreachable": true
}
10.0.0.6 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: sysadmin@10.0.0.6: Permission denied (publickey).",
    "unreachable": true
}
root@736da561d420:~# ansible -m ping all
10.0.0.5 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: sysadmin@10.0.0.5: Permission denied (publickey).",
    "unreachable": true
}
10.0.0.6 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: sysadmin@10.0.0.6: Permission denied (publickey).",
    "unreachable": true
}
root@736da561d420:~# nano /etc/ansible/ansible.cfg
root@736da561d420:~# ansible -m ping all
10.0.0.6 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
10.0.0.5 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: azureuser@10.0.0.5: Permission denied (publickey).",
    "unreachable": true
}
root@736da561d420:~# nano /etc/ansible/ansible.cfg
root@736da561d420:~# nano /etc/ansible/hosts
root@736da561d420:~# ansible -m ping all
10.0.0.6 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
10.0.0.5 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: azureuser@10.0.0.5: Permission denied (publickey).",
    "unreachable": true
}
root@736da561d420:~# ansible -m ping all
10.0.0.6 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
10.0.0.5 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
root@736da561d420:~# docker container list -a
bash: docker: command not found
root@736da561d420:~# exit
exit
root@Jump-Box-Provisioner:/home/azureuser# docker container list -a
CONTAINER ID   IMAGE                           COMMAND                  CREATED             STATUS                           PORTS     NAMES
736da561d420   cyberxsecurity/ansible          "/bin/sh -c /bin/bas…"   About an hour ago   Exited (127) 21 seconds ago                laughing_rosalind
f2d3cf099775   cyberxsecurity/ansible:latest   "/bin/sh -c /bin/bas…"   About an hour ago   Exited (127) About an hour ago             pensive_hopper
root@Jump-Box-Provisioner:/home/azureuser# docker start laughing_rosalind
laughing_rosalind
root@Jump-Box-Provisioner:/home/azureuser# docker attach laughing_rosalind
root@736da561d420:~# nano /etc/ansible/pentest.yml
root@736da561d420:~# nano /etc/ansible/pentest.yml
root@736da561d420:~# nano /etc/ansible/pentest.yml


Use "fg" to return to nano.

[1]+  Stopped                 nano /etc/ansible/pentest.yml
root@736da561d420:~# nano /etc/ansible/pentest.yml
root@736da561d420:~# ansible-playbook /etc/ansible/pentest.yml
[WARNING]: ansible.utils.display.initialize_locale has not been called, this may result in incorrectly calculated text widths that can cause Display to print incorrect
line lengths

PLAY [Config Web VM with Docker] *******************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************
ok: [10.0.0.6]
ok: [10.0.0.5]

TASK [docker.io] ***********************************************************************************************************************************************************
changed: [10.0.0.5]
changed: [10.0.0.6]

TASK [Install pip3] ********************************************************************************************************************************************************
changed: [10.0.0.6]
changed: [10.0.0.5]

TASK [Install Docker python module] ****************************************************************************************************************************************
changed: [10.0.0.5]
changed: [10.0.0.6]

TASK [download and launch a docker web container] **************************************************************************************************************************
[DEPRECATION WARNING]: The container_default_behavior option will change its default value from "compatibility" to "no_defaults" in community.docker 2.0.0. To remove this
warning, please specify an explicit value for it now. This feature will be removed from community.docker in version 2.0.0. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
changed: [10.0.0.6]
changed: [10.0.0.5]

TASK [Enable docker service] ***********************************************************************************************************************************************
ok: [10.0.0.6]
ok: [10.0.0.5]

PLAY RECAP *****************************************************************************************************************************************************************
10.0.0.5                   : ok=6    changed=4    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
10.0.0.6                   : ok=6    changed=4    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

root@736da561d420:~# ssh azureuser@10.0.0.6
Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1055-azure x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

 System information disabled due to load higher than 1.0


10 updates can be applied immediately.
10 of these updates are standard security updates.
To see these additional updates run: apt list --upgradable

New release '20.04.2 LTS' available.
Run 'do-release-upgrade' to upgrade to it.


Last login: Sat Jul 24 05:31:10 2021 from 10.0.0.4
azureuser@Web-2:~$ curl localhost/setup.php
<!DOCTYPE html>

<html lang="en-GB">

        <head>
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

                <title>Setup :: Damn Vulnerable Web Application (DVWA) v1.10 *Development*</title>

                <link rel="stylesheet" type="text/css" href="dvwa/css/main.css" />

                <link rel="icon" type="\image/ico" href="favicon.ico" />

                <script type="text/javascript" src="dvwa/js/dvwaPage.js"></script>

        </head>

        <body class="home">
                <div id="container">

                        <div id="header">

                                <img src="dvwa/images/logo.png" alt="Damn Vulnerable Web Application" />

                        </div>

                        <div id="main_menu">

                                <div id="main_menu_padded">
                                <ul class="menuBlocks"><li class="selected"><a href="setup.php">Setup DVWA</a></li>
<li class=""><a href="instructions.php">Instructions</a></li>
</ul><ul class="menuBlocks"><li class=""><a href="about.php">About</a></li>
</ul>
                                </div>

                        </div>

                        <div id="main_body">


<div class="body_padded">
        <h1>Database Setup <img src="dvwa/images/spanner.png" /></h1>

        <p>Click on the 'Create / Reset Database' button below to create or reset your database.<br />
        If you get an error make sure you have the correct user credentials in: <em>/var/www/html/config/config.inc.php</em></p>

        <p>If the database already exists, <em>it will be cleared and the data will be reset</em>.<br />
        You can also use this to reset the administrator credentials ("<em>admin</em> // <em>password</em>") at any stage.</p>
        <hr />
        <br />

        <h2>Setup Check</h2>

        Operating system: <em>*nix</em><br />
        Backend database: <em>MySQL</em><br />
        PHP version: <em>7.0.33-0+deb9u10</em><br />
        <br />
        Web Server SERVER_NAME: <em>localhost</em><br />
        <br />
        PHP function display_errors: <em>Disabled</em><br />
        PHP function safe_mode: <span class="success">Disabled</span><br/ >
        PHP function allow_url_include: <span class="success">Enabled</span><br/ >
        PHP function allow_url_fopen: <span class="success">Enabled</span><br />
        PHP function magic_quotes_gpc: <span class="success">Disabled</span><br />
        PHP module gd: <span class="success">Installed</span><br />
        PHP module mysql: <span class="success">Installed</span><br />
        PHP module pdo_mysql: <span class="success">Installed</span><br />
        <br />
        MySQL username: <em>app</em><br />
        MySQL password: <em>******</em><br />
        MySQL database: <em>dvwa</em><br />
        MySQL host: <em>127.0.0.1</em><br />
        <br />
        reCAPTCHA key: <span class="failure">Missing</span><br />
        <br />
        [User: www-data] Writable folder /var/www/html/hackable/uploads/: <span class="success">Yes</span><br />
        [User: www-data] Writable file /var/www/html/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt: <span class="success">Yes</span><br />
        <br />
        <br />
        [User: www-data] Writable folder /var/www/html/config: <span class="success">Yes</span>
        <br />
        <i><span class="failure">Status in red</span>, indicate there will be an issue when trying to complete some modules.</i><br />
        <br />
        If you see disabled on either <i>allow_url_fopen</i> or <i>allow_url_include</i>, set the following in your php.ini file and restart Apache.<br />
        <pre><code>allow_url_fopen = On
allow_url_include = On</code></pre>
        These are only required for the file inclusion labs so unless you want to play with those, you can ignore them.

        <br /><br /><br />

        <!-- Create db button -->
        <form action="#" method="post">
                <input name="create_db" type="submit" value="Create / Reset Database">
                <input type='hidden' name='user_token' value='2a72700a31d852fd3a3d69c0a1ad6724' />
        </form>
        <br />
        <hr />
</div>
                                <br /><br />


                        </div>

                        <div class="clear">
                        </div>

                        <div id="system_info">

                        </div>

                        <div id="footer">

                                <p>Damn Vulnerable Web Application (DVWA) v1.10 *Development*</p>
                                <script src='/dvwa/js/add_event_listeners.js'></script>

                        </div>

                </div>

        </body>

</html>azureuser@Web-2:~$ client_loop: send disconnect: Broken pipe
root@736da561d420:~# ssh azureuser@10.0.0.7
The authenticity of host '10.0.0.7 (10.0.0.7)' can't be established.
ECDSA key fingerprint is SHA256:/9tzI4dWNbAWZSzn/JMH1Dmmq6JV12l3rF+zyxO5Yps.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '10.0.0.7' (ECDSA) to the list of known hosts.
Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1055-azure x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Sat Jul 24 06:43:23 UTC 2021

  System load:  0.31              Processes:           116
  Usage of /:   4.6% of 28.90GB   Users logged in:     0
  Memory usage: 20%               IP address for eth0: 10.0.0.7
  Swap usage:   0%

0 updates can be applied immediately.



The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

azureuser@Web-3:~$ exit
logout
Connection to 10.0.0.7 closed.
root@736da561d420:~# nano /etc/ansible/hosts
root@736da561d420:~# ansible all -m ping
10.0.0.7 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
10.0.0.6 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
10.0.0.5 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
root@736da561d420:~# ansible-playbook your-playbook.yml
ERROR! the playbook: your-playbook.yml could not be found
root@736da561d420:~# nano /etc/ansible/ansible.cfg
root@736da561d420:~# nano /etc/ansible/pentest.yml
root@736da561d420:~# ansible-playbook your-playbook.yml
ERROR! the playbook: your-playbook.yml could not be found
root@736da561d420:~# nano /etc/ansible/pentest.yml
root@736da561d420:~# ansible-playbook /etc/ansible/pentest.yml
[WARNING]: ansible.utils.display.initialize_locale has not been called, this may result in incorrectly calculated text widths that can cause Display to print incorrect
line lengths

PLAY [Config Web VM with Docker] *******************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************
ok: [10.0.0.6]
ok: [10.0.0.5]
ok: [10.0.0.7]

TASK [docker.io] ***********************************************************************************************************************************************************
ok: [10.0.0.5]
ok: [10.0.0.6]
changed: [10.0.0.7]

TASK [Install pip3] ********************************************************************************************************************************************************
ok: [10.0.0.5]
ok: [10.0.0.6]
changed: [10.0.0.7]

TASK [Install Docker python module] ****************************************************************************************************************************************
ok: [10.0.0.5]
ok: [10.0.0.6]
changed: [10.0.0.7]

TASK [download and launch a docker web container] **************************************************************************************************************************
[DEPRECATION WARNING]: The container_default_behavior option will change its default value from "compatibility" to "no_defaults" in community.docker 2.0.0. To remove this
warning, please specify an explicit value for it now. This feature will be removed from community.docker in version 2.0.0. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
ok: [10.0.0.5]
ok: [10.0.0.6]
changed: [10.0.0.7]

TASK [Enable docker service] ***********************************************************************************************************************************************
ok: [10.0.0.6]
ok: [10.0.0.5]
ok: [10.0.0.7]

PLAY RECAP *****************************************************************************************************************************************************************
10.0.0.5                   : ok=6    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
10.0.0.6                   : ok=6    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
10.0.0.7                   : ok=6    changed=4    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

root@736da561d420:~# ssh azureuser@10.0.0.7
Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1055-azure x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

 System information disabled due to load higher than 1.0


10 updates can be applied immediately.
10 of these updates are standard security updates.
To see these additional updates run: apt list --upgradable

New release '20.04.2 LTS' available.
Run 'do-release-upgrade' to upgrade to it.


Last login: Sat Jul 24 06:53:54 2021 from 10.0.0.4
azureuser@Web-3:~$ curl localhost/setup.php
<!DOCTYPE html>

<html lang="en-GB">

        <head>
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

                <title>Setup :: Damn Vulnerable Web Application (DVWA) v1.10 *Development*</title>

                <link rel="stylesheet" type="text/css" href="dvwa/css/main.css" />

                <link rel="icon" type="\image/ico" href="favicon.ico" />

                <script type="text/javascript" src="dvwa/js/dvwaPage.js"></script>

        </head>

        <body class="home">
                <div id="container">

                        <div id="header">

                                <img src="dvwa/images/logo.png" alt="Damn Vulnerable Web Application" />

                        </div>

                        <div id="main_menu">

                                <div id="main_menu_padded">
                                <ul class="menuBlocks"><li class="selected"><a href="setup.php">Setup DVWA</a></li>
<li class=""><a href="instructions.php">Instructions</a></li>
</ul><ul class="menuBlocks"><li class=""><a href="about.php">About</a></li>
</ul>
                                </div>

                        </div>

                        <div id="main_body">


<div class="body_padded">
        <h1>Database Setup <img src="dvwa/images/spanner.png" /></h1>

        <p>Click on the 'Create / Reset Database' button below to create or reset your database.<br />
        If you get an error make sure you have the correct user credentials in: <em>/var/www/html/config/config.inc.php</em></p>

        <p>If the database already exists, <em>it will be cleared and the data will be reset</em>.<br />
        You can also use this to reset the administrator credentials ("<em>admin</em> // <em>password</em>") at any stage.</p>
        <hr />
        <br />

        <h2>Setup Check</h2>

        Operating system: <em>*nix</em><br />
        Backend database: <em>MySQL</em><br />
        PHP version: <em>7.0.33-0+deb9u10</em><br />
        <br />
        Web Server SERVER_NAME: <em>localhost</em><br />
        <br />
        PHP function display_errors: <em>Disabled</em><br />
        PHP function safe_mode: <span class="success">Disabled</span><br/ >
        PHP function allow_url_include: <span class="success">Enabled</span><br/ >
        PHP function allow_url_fopen: <span class="success">Enabled</span><br />
        PHP function magic_quotes_gpc: <span class="success">Disabled</span><br />
        PHP module gd: <span class="success">Installed</span><br />
        PHP module mysql: <span class="success">Installed</span><br />
        PHP module pdo_mysql: <span class="success">Installed</span><br />
        <br />
        MySQL username: <em>app</em><br />
        MySQL password: <em>******</em><br />
        MySQL database: <em>dvwa</em><br />
        MySQL host: <em>127.0.0.1</em><br />
        <br />
        reCAPTCHA key: <span class="failure">Missing</span><br />
        <br />
        [User: www-data] Writable folder /var/www/html/hackable/uploads/: <span class="success">Yes</span><br />
        [User: www-data] Writable file /var/www/html/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt: <span class="success">Yes</span><br />
        <br />
        <br />
        [User: www-data] Writable folder /var/www/html/config: <span class="success">Yes</span>
        <br />
        <i><span class="failure">Status in red</span>, indicate there will be an issue when trying to complete some modules.</i><br />
        <br />
        If you see disabled on either <i>allow_url_fopen</i> or <i>allow_url_include</i>, set the following in your php.ini file and restart Apache.<br />
        <pre><code>allow_url_fopen = On
allow_url_include = On</code></pre>
        These are only required for the file inclusion labs so unless you want to play with those, you can ignore them.

        <br /><br /><br />

        <!-- Create db button -->
        <form action="#" method="post">
                <input name="create_db" type="submit" value="Create / Reset Database">
                <input type='hidden' name='user_token' value='46ec47a8c59c55ad2edbdc35577a727a' />
        </form>
        <br />
        <hr />
</div>
                                <br /><br />


                        </div>

                        <div class="clear">
                        </div>

                        <div id="system_info">

                        </div>

                        <div id="footer">

                                <p>Damn Vulnerable Web Application (DVWA) v1.10 *Development*</p>
                                <script src='/dvwa/js/add_event_listeners.js'></script>

                        </div>

                </div>

        </body>

</html>azureuser@Web-3:~$ Connection to 10.0.0.7 closed by remote host.
Connection to 10.0.0.7 closed.
root@736da561d420:~# Connection to 20.98.128.246 closed by remote host.
Connection to 20.98.128.246 closed.

19178@DESKTOP-CD6E9HI MINGW64 ~
$
                        </div>

                        <div id="main_body">


<div class="body_padded">
        <h1>Database Setup <img src="dvwa/images/spanner.png" /></h1>

        <p>Click on the 'Create / Reset Database' button below to create or reset your database.<br />
        If you get an error make sure you have the correct user credentials in: <em>/var/www/html/config/config.inc.php</em></p>

        <p>If the database already exists, <em>it will be cleared and the data will be reset</em>.<br />
        You can also use this to reset the administrator credentials ("<em>admin</em> // <em>password</em>") at any stage.</p>
        <hr />
        <br />

        <h2>Setup Check</h2>

        Operating system: <em>*nix</em><br />
        Backend database: <em>MySQL</em><br />
        PHP version: <em>7.0.33-0+deb9u10</em><br />
        <br />
        Web Server SERVER_NAME: <em>localhost</em><br />
        <br />
        PHP function display_errors: <em>Disabled</em><br />
        PHP function safe_mode: <span class="success">Disabled</span><br/ >
        PHP function allow_url_include: <span class="success">Enabled</span><br/ >
        PHP function allow_url_fopen: <span class="success">Enabled</span><br />
        PHP function magic_quotes_gpc: <span class="success">Disabled</span><br />
        PHP module gd: <span class="success">Installed</span><br />
        PHP module mysql: <span class="success">Installed</span><br />
        PHP module pdo_mysql: <span class="success">Installed</span><br />

19178@DESKTOP-CD6E9HI MINGW64 ~
$

19178@DESKTOP-CD6E9HI MINGW64 ~
$                         </div>
bash: syntax error near unexpected token `newline'

19178@DESKTOP-CD6E9HI MINGW64 ~
$

19178@DESKTOP-CD6E9HI MINGW64 ~
$                         <div id="main_body">
bash: syntax error near unexpected token `newline'

19178@DESKTOP-CD6E9HI MINGW64 ~
$

19178@DESKTOP-CD6E9HI MINGW64 ~
$

19178@DESKTOP-CD6E9HI MINGW64 ~
$ <div class="body_padded">
bash: syntax error near unexpected token `newline'

19178@DESKTOP-CD6E9HI MINGW64 ~
$         <h1>Database Setup <img src="dvwa/images/spanner.png" /></h1>
bash: syntax error near unexpected token `<'

19178@DESKTOP-CD6E9HI MINGW64 ~
$

19178@DESKTOP-CD6E9HI MINGW64 ~
set your database.<br />e 'Create / Reset Database' button below to create or res
bash: syntax error near unexpected token `newline'

19178@DESKTOP-CD6E9HI MINGW64 ~
: <em>/var/www/html/config/config.inc.php</em></p>he correct user credentials in:
bash: syntax error near unexpected token `<'

19178@DESKTOP-CD6E9HI MINGW64 ~
$

19178@DESKTOP-CD6E9HI MINGW64 ~
 will be reset</em>.<br />se already exists, <em>it will be cleared and the data
bash: syntax error near unexpected token `newline'

19178@DESKTOP-CD6E9HI MINGW64 ~
in</em> // <em>password</em>") at any stage.</p>inistrator credentials ("<em>admi
bash: syntax error near unexpected token `('

19178@DESKTOP-CD6E9HI MINGW64 ~
$         <hr />
bash: syntax error near unexpected token `newline'

19178@DESKTOP-CD6E9HI MINGW64 ~
$         <br />
bash: syntax error near unexpected token `newline'

19178@DESKTOP-CD6E9HI MINGW64 ~
$

19178@DESKTOP-CD6E9HI MINGW64 ~
$         <h2>Setup Check</h2>
bash: syntax error near unexpected token `newline'

19178@DESKTOP-CD6E9HI MINGW64 ~
$

19178@DESKTOP-CD6E9HI MINGW64 ~
$         Operating system: <em>*nix</em><br />
bash: syntax error near unexpected token `<'

19178@DESKTOP-CD6E9HI MINGW64 ~
$         Backend database: <em>MySQL</em><br />
bash: syntax error near unexpected token `<'

19178@DESKTOP-CD6E9HI MINGW64 ~
$         PHP version: <em>7.0.33-0+deb9u10</em><br />
bash: syntax error near unexpected token `<'

19178@DESKTOP-CD6E9HI MINGW64 ~
$         <br />
bash: syntax error near unexpected token `newline'

19178@DESKTOP-CD6E9HI MINGW64 ~
$         Web Server SERVER_NAME: <em>localhost</em><br />
bash: syntax error near unexpected token `<'

19178@DESKTOP-CD6E9HI MINGW64 ~
$         <br />
bash: syntax error near unexpected token `newline'

19178@DESKTOP-CD6E9HI MINGW64 ~
$         PHP function display_errors: <em>Disabled</em><br />
bash: syntax error near unexpected token `<'

19178@DESKTOP-CD6E9HI MINGW64 ~
$         PHP function safe_mode: <span class="success">Disabled</span><br/ >
bash: syntax error near unexpected token `<'

19178@DESKTOP-CD6E9HI MINGW64 ~
r/ >      PHP function allow_url_include: <span class="success">Enabled</span><br
bash: syntax error near unexpected token `<'

19178@DESKTOP-CD6E9HI MINGW64 ~
/>        PHP function allow_url_fopen: <span class="success">Enabled</span><br /
bash: syntax error near unexpected token `<'

19178@DESKTOP-CD6E9HI MINGW64 ~
r />      PHP function magic_quotes_gpc: <span class="success">Disabled</span><br
bash: syntax error near unexpected token `<'

19178@DESKTOP-CD6E9HI MINGW64 ~
$         PHP module gd: <span class="success">Installed</span><br />
bash: syntax error near unexpected token `<'

19178@DESKTOP-CD6E9HI MINGW64 ~
$         PHP module mysql: <span class="success">Installed</span><br />
bash: syntax error near unexpected token `<'

19178@DESKTOP-CD6E9HI MINGW64 ~
$         PHP module pdo_mysql: <span class="success">Installed</span><br />
bash: syntax error near unexpected token `<'

19178@DESKTOP-CD6E9HI MINGW64 ~
$ ssh azureuser@20.98.128.246
Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1055-azure x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Sat Jul 24 21:48:33 UTC 2021

  System load:  0.0               Processes:              109
  Usage of /:   9.1% of 28.90GB   Users logged in:        0
  Memory usage: 28%               IP address for eth0:    10.0.0.4
  Swap usage:   0%                IP address for docker0: 172.17.0.1

 * Super-optimized for small spaces - read how we shrank the memory
   footprint of MicroK8s to make it the smallest full K8s around.

   https://ubuntu.com/blog/microk8s-memory-optimisation

0 updates can be applied immediately.

New release '20.04.2 LTS' available.
Run 'do-release-upgrade' to upgrade to it.


Last login: Sat Jul 24 03:49:30 2021 from 173.52.52.5
azureuser@Jump-Box-Provisioner:~$ sudo docer ps
sudo: docer: command not found
azureuser@Jump-Box-Provisioner:~$ sudo docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
azureuser@Jump-Box-Provisioner:~$ sudo docker container list -a
CONTAINER ID   IMAGE                           COMMAND                  CREATED        STATUS                      PORTS     NAMES
736da561d420   cyberxsecurity/ansible          "/bin/sh -c /bin/bas…"   18 hours ago   Exited (137) 15 hours ago             laughing_rosalind
f2d3cf099775   cyberxsecurity/ansible:latest   "/bin/sh -c /bin/bas…"   18 hours ago   Exited (127) 18 hours ago             pensive_hopper
azureuser@Jump-Box-Provisioner:~$ sudo docker start laughing_rosalind
laughing_rosalind
azureuser@Jump-Box-Provisioner:~$ sudo docker container attach laughing_rosalind
root@736da561d420:~# ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDTL84ehIFnIPcx0OgjNaFt5mYFJalhX74KUyIZsOsijBiVjcX9g06VqBAlw4c/ZSYvuxMkrhp7KCQwLESby4qgFoL+yUYyxWeV+QETJPkIWatZ/0Tv/w1B38E0x5p7Cfy2kye0gA5UwDvLXB/him9wyU/SwTC6QZtbn26nbdgsUEShNcdzJtB6p5/QL1Ut6oKEo2O5aJRTBdYw/tuYqFnBl3pE01cXCnUqL3a1rz22PxHBdK8qvq+gWaaZcAvkTuicyB1JM0b/I0pkZziC/pKDmvbSAnob/6mIvJD7NNlsT4QEsyyIKkPDRTVRv4R17RGXvWKsKg14B2p2bz1iTc2guKvmQeYBxj+SDVq5hDEVMbOJzgLFFtpFBXYbb2ddzWzfXw/7R3xZ34Z0vJXZqn7W/A0COUbH157YY13sKfOjzKuY9uuvaHuMu3sbu5gmd2+8Gv5KdDDyqE/xun+miqTM2xi3dBBI3TdsR1+BcySRHQ4VUvYknW6xd/VyaMTYLT8= root@736da561d420
bash: ssh-rsa: command not found
root@736da561d420:~# cat ~/.ssh/id_rsa.pub
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDTL84ehIFnIPcx0OgjNaFt5mYFJalhX74KUyIZsOsijBiVjcX9g06VqBAlw4c/ZSYvuxMkrhp7KCQwLESby4qgFoL+yUYyxWeV+QETJPkIWatZ/0Tv/w1B38E0x5p7Cfy2kye0gA5UwDvLXB/him9wyU/SwTC6QZtbn26nbdgsUEShNcdzJtB6p5/QL1Ut6oKEo2O5aJRTBdYw/tuYqFnBl3pE01cXCnUqL3a1rz22PxHBdK8qvq+gWaaZcAvkTuicyB1JM0b/I0pkZziC/pKDmvbSAnob/6mIvJD7NNlsT4QEsyyIKkPDRTVRv4R17RGXvWKsKg14B2p2bz1iTc2guKvmQeYBxj+SDVq5hDEVMbOJzgLFFtpFBXYbb2ddzWzfXw/7R3xZ34Z0vJXZqn7W/A0COUbH157YY13sKfOjzKuY9uuvaHuMu3sbu5gmd2+8Gv5KdDDyqE/xun+miqTM2xi3dBBI3TdsR1+BcySRHQ4VUvYknW6xd/VyaMTYLT8= root@736da561d420
root@736da561d420:~# ssh azureuser@40.78.109.238
The authenticity of host '40.78.109.238 (40.78.109.238)' can't be established.
ECDSA key fingerprint is SHA256:0088BpaMbkQ2GhJEl5vUDUmNkCCW7g1FthnPOOR7qkA.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '40.78.109.238' (ECDSA) to the list of known hosts.
Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1055-azure x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Sat Jul 24 22:07:59 UTC 2021

  System load:  0.2               Processes:           129
  Usage of /:   4.7% of 28.90GB   Users logged in:     0
  Memory usage: 2%                IP address for eth0: 10.1.0.4
  Swap usage:   0%

 * Super-optimized for small spaces - read how we shrank the memory
   footprint of MicroK8s to make it the smallest full K8s around.

   https://ubuntu.com/blog/microk8s-memory-optimisation

0 updates can be applied immediately.



The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

azureuser@ELK-SERVER:~$ cd /etc/ansible/
-bash: cd: /etc/ansible/: No such file or directory
azureuser@ELK-SERVER:~$ ls
azureuser@ELK-SERVER:~$ cd /etc/ansible/
-bash: cd: /etc/ansible/: No such file or directory
azureuser@ELK-SERVER:~$ exit
logout
Connection to 40.78.109.238 closed.
root@736da561d420:~# cd /etc/ansible/
root@736da561d420:/etc/ansible# ls
ansible.cfg  hosts  pentest.yml
root@736da561d420:/etc/ansible# nano hosts
root@736da561d420:/etc/ansible# ls
ansible.cfg  hosts  pentest.yml
root@736da561d420:/etc/ansible# cd playbook/
bash: cd: playbook/: No such file or directory
root@736da561d420:/etc/ansible# ls
ansible.cfg  hosts  pentest.yml
root@736da561d420:/etc/ansible# cd playbook
bash: cd: playbook: No such file or directory
root@736da561d420:/etc/ansible# ls
ansible.cfg  hosts  pentest.yml
root@736da561d420:/etc/ansible# nano elk_red.yml
root@736da561d420:/etc/ansible# ls
ansible.cfg  elk_red.yml  hosts  pentest.yml
root@736da561d420:/etc/ansible# nano elk_red.yml
root@736da561d420:/etc/ansible# ansible-playbook elk_red.yml
ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  found character that cannot start any token

The error appears to be in '/etc/ansible/elk_red.yml': line 7, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


        - name: Use more memory
^ here
There appears to be a tab character at the start of the line.

YAML does not use tabs for formatting. Tabs should be replaced with spaces.

For example:
    - name: update tooling
      vars:
        version: 1.2.3
#    ^--- there is a tab there.

Should be written as:
    - name: update tooling
      vars:
        version: 1.2.3
# ^--- all spaces here.
root@736da561d420:/etc/ansible# nano elk_red.yml
root@736da561d420:/etc/ansible# ansible-playbook elk_red.yml
ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  found character that cannot start any token

The error appears to be in '/etc/ansible/elk_red.yml': line 6, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
        - name: Use more memory
^ here
There appears to be a tab character at the start of the line.

YAML does not use tabs for formatting. Tabs should be replaced with spaces.

For example:
    - name: update tooling
      vars:
        version: 1.2.3
#    ^--- there is a tab there.

Should be written as:
    - name: update tooling
      vars:
        version: 1.2.3
# ^--- all spaces here.
root@736da561d420:/etc/ansible# nano elk_red.yml
root@736da561d420:/etc/ansible# ansible-playbook elk_red.yml
[WARNING]: Could not match supplied host pattern, ignoring: elkservers
[WARNING]: ansible.utils.display.initialize_locale has not been called, this may result in incorrectly calculated text widths that can cause Display to print incorrect
line lengths

PLAY [Config elk vm with Docker] *******************************************************************************************************************************************
skipping: no hosts matched

PLAY RECAP *****************************************************************************************************************************************************************

root@736da561d420:/etc/ansible# nano hosts
root@736da561d420:/etc/ansible# ansible-playbook elk_red.yml
[WARNING]: Could not match supplied host pattern, ignoring: elkservers
[WARNING]: ansible.utils.display.initialize_locale has not been called, this may result in incorrectly calculated text widths that can cause Display to print incorrect
line lengths

PLAY [Config elk vm with Docker] *******************************************************************************************************************************************
skipping: no hosts matched

PLAY RECAP *****************************************************************************************************************************************************************

root@736da561d420:/etc/ansible# nano hosts
root@736da561d420:/etc/ansible# ls
ansible.cfg  elk_red.yml  hosts  pentest.yml
root@736da561d420:/etc/ansible# ansible-playbook elk_red.yml
[WARNING]: ansible.utils.display.initialize_locale has not been called, this may result in incorrectly calculated text widths that can cause Display to print incorrect
line lengths

PLAY [Config elk vm with Docker] *******************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************
^[[A^[[Bok: [10.1.0.4]

TASK [Use more memory] *****************************************************************************************************************************************************
changed: [10.1.0.4]

TASK [docker.io] ***********************************************************************************************************************************************************
changed: [10.1.0.4]

TASK [Install pip3] ********************************************************************************************************************************************************
changed: [10.1.0.4]

TASK [Install Docker python module] ****************************************************************************************************************************************
changed: [10.1.0.4]

PLAY RECAP *****************************************************************************************************************************************************************
10.1.0.4                   : ok=5    changed=4    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

root@736da561d420:/etc/ansible# nano elk_red.yml
root@736da561d420:/etc/ansible# nano elk_red.yml
root@736da561d420:/etc/ansible# ansible-playbook elk_red.yml
ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to be in '/etc/ansible/elk_red.yml': line 29, column 54, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


     - name: download & launch a docker elk container:
                                                     ^ here
root@736da561d420:/etc/ansible# nano elk_red.yml
root@736da561d420:/etc/ansible# ansible-playbook elk_red.yml
[WARNING]: ansible.utils.display.initialize_locale has not been called, this may result in incorrectly calculated text widths that can cause Display to print incorrect
line lengths

PLAY [Config elk vm with Docker] *******************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [Use more memory] *****************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [docker.io] ***********************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [Install pip3] ********************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [Install Docker python module] ****************************************************************************************************************************************
ok: [10.1.0.4]

TASK [download & launch a docker elk container] ****************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: UnboundLocalError: local variable 'port_binds' referenced before assignment
fatal: [10.1.0.4]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 10.1.0.4 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/azureuser/.ansible/tmp/ansible-tmp-1627167399.6662996-156-66921507150263/AnsiballZ_docker_container.py\", line 100, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/azureuser/.ansible/tmp/ansible-tmp-1627167399.6662996-156-66921507150263/AnsiballZ_docker_container.py\", line 92, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/azureuser/.ansible/tmp/ansible-tmp-1627167399.6662996-156-66921507150263/AnsiballZ_docker_container.py\", line 41, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib/python3.6/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.6/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_docker_container_payload_f3un2syp/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 3619, in <module>\r\n  File \"/tmp/ansible_docker_container_payload_f3un2syp/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 3608, in main\r\n  File \"/tmp/ansible_docker_container_payload_f3un2syp/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 2754, in __init__\r\n  File \"/tmp/ansible_docker_container_payload_f3un2syp/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1422, in __init__\r\n  File \"/tmp/ansible_docker_container_payload_f3un2syp/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1789, in _parse_publish_ports\r\nUnboundLocalError: local variable 'port_binds' referenced before assignment\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *****************************************************************************************************************************************************************
10.1.0.4                   : ok=5    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

root@736da561d420:/etc/ansible# nano elk_red.yml
root@736da561d420:/etc/ansible# ansible-playbook elk_red.yml
[WARNING]: ansible.utils.display.initialize_locale has not been called, this may result in incorrectly calculated text widths that can cause Display to print incorrect
line lengths

PLAY [Config elk vm with Docker] *******************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [Use more memory] *****************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [docker.io] ***********************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [Install pip3] ********************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [Install Docker python module] ****************************************************************************************************************************************
ok: [10.1.0.4]

TASK [download & launch a docker elk container] ****************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: UnboundLocalError: local variable 'port_binds' referenced before assignment
fatal: [10.1.0.4]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 10.1.0.4 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/azureuser/.ansible/tmp/ansible-tmp-1627167733.5405424-220-267691275451430/AnsiballZ_docker_container.py\", line 100, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/azureuser/.ansible/tmp/ansible-tmp-1627167733.5405424-220-267691275451430/AnsiballZ_docker_container.py\", line 92, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/azureuser/.ansible/tmp/ansible-tmp-1627167733.5405424-220-267691275451430/AnsiballZ_docker_container.py\", line 41, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib/python3.6/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.6/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_docker_container_payload_ezwf33zh/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 3619, in <module>\r\n  File \"/tmp/ansible_docker_container_payload_ezwf33zh/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 3608, in main\r\n  File \"/tmp/ansible_docker_container_payload_ezwf33zh/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 2754, in __init__\r\n  File \"/tmp/ansible_docker_container_payload_ezwf33zh/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1422, in __init__\r\n  File \"/tmp/ansible_docker_container_payload_ezwf33zh/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1789, in _parse_publish_ports\r\nUnboundLocalError: local variable 'port_binds' referenced before assignment\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *****************************************************************************************************************************************************************
10.1.0.4                   : ok=5    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

root@736da561d420:/etc/ansible# nano hosts
root@736da561d420:/etc/ansible# nano elk_red.yml
root@736da561d420:/etc/ansible# nano elk_red.yml
root@736da561d420:/etc/ansible# ansible-playbook elk_red.yml
[WARNING]: ansible.utils.display.initialize_locale has not been called, this may result in incorrectly calculated text widths that can cause Display to print incorrect
line lengths

PLAY [Config elk vm with Docker] *******************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [Use more memory] *****************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [docker.io] ***********************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [Install pip3] ********************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [Install Docker python module] ****************************************************************************************************************************************
ok: [10.1.0.4]

TASK [download and launch a docker elk container] **************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: UnboundLocalError: local variable 'port_binds' referenced before assignment
fatal: [10.1.0.4]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 10.1.0.4 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/azureuser/.ansible/tmp/ansible-tmp-1627167910.1064334-286-155386420997956/AnsiballZ_docker_container.py\", line 100, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/azureuser/.ansible/tmp/ansible-tmp-1627167910.1064334-286-155386420997956/AnsiballZ_docker_container.py\", line 92, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/azureuser/.ansible/tmp/ansible-tmp-1627167910.1064334-286-155386420997956/AnsiballZ_docker_container.py\", line 41, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib/python3.6/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.6/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_docker_container_payload_l666wd_t/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 3619, in <module>\r\n  File \"/tmp/ansible_docker_container_payload_l666wd_t/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 3608, in main\r\n  File \"/tmp/ansible_docker_container_payload_l666wd_t/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 2754, in __init__\r\n  File \"/tmp/ansible_docker_container_payload_l666wd_t/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1422, in __init__\r\n  File \"/tmp/ansible_docker_container_payload_l666wd_t/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1789, in _parse_publish_ports\r\nUnboundLocalError: local variable 'port_binds' referenced before assignment\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *****************************************************************************************************************************************************************
10.1.0.4                   : ok=5    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

root@736da561d420:/etc/ansible# nano elk_red.yml
root@736da561d420:/etc/ansible# ansible-playbook elk_red.yml
[WARNING]: ansible.utils.display.initialize_locale has not been called, this may result in incorrectly calculated text widths that can cause Display to print incorrect
line lengths

PLAY [Config elk vm with Docker] *******************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [Use more memory] *****************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [docker.io] ***********************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [Install pip3] ********************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [Install Docker python module] ****************************************************************************************************************************************
ok: [10.1.0.4]

TASK [download and launch a docker elk container] **************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: UnboundLocalError: local variable 'port_binds' referenced before assignment
fatal: [10.1.0.4]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 10.1.0.4 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/azureuser/.ansible/tmp/ansible-tmp-1627168353.4523351-350-212064246870539/AnsiballZ_docker_container.py\", line 100, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/azureuser/.ansible/tmp/ansible-tmp-1627168353.4523351-350-212064246870539/AnsiballZ_docker_container.py\", line 92, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/azureuser/.ansible/tmp/ansible-tmp-1627168353.4523351-350-212064246870539/AnsiballZ_docker_container.py\", line 41, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib/python3.6/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.6/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_docker_container_payload_rfqh0g2r/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 3619, in <module>\r\n  File \"/tmp/ansible_docker_container_payload_rfqh0g2r/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 3608, in main\r\n  File \"/tmp/ansible_docker_container_payload_rfqh0g2r/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 2754, in __init__\r\n  File \"/tmp/ansible_docker_container_payload_rfqh0g2r/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1422, in __init__\r\n  File \"/tmp/ansible_docker_container_payload_rfqh0g2r/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1789, in _parse_publish_ports\r\nUnboundLocalError: local variable 'port_binds' referenced before assignment\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *****************************************************************************************************************************************************************
10.1.0.4                   : ok=5    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

root@736da561d420:/etc/ansible# nano elk_red.yml
root@736da561d420:/etc/ansible# ansible-playbook elk_red.yml
ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to be in '/etc/ansible/elk_red.yml': line 32, column 25, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

         name: elk
         image: sebp/elk: 761
                        ^ here
root@736da561d420:/etc/ansible# nano elk_red.yml
root@736da561d420:/etc/ansible# ansible-playbook elk_red.yml
[WARNING]: ansible.utils.display.initialize_locale has not been called, this may result in incorrectly calculated text widths that can cause Display to print incorrect
line lengths

PLAY [Config elk vm with Docker] *******************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [Use more memory] *****************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [docker.io] ***********************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [Install pip3] ********************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [Install Docker python module] ****************************************************************************************************************************************
ok: [10.1.0.4]

TASK [download and launch a docker elk container] **************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: UnboundLocalError: local variable 'port_binds' referenced before assignment
fatal: [10.1.0.4]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 10.1.0.4 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/azureuser/.ansible/tmp/ansible-tmp-1627168524.2112486-419-271310772692122/AnsiballZ_docker_container.py\", line 100, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/azureuser/.ansible/tmp/ansible-tmp-1627168524.2112486-419-271310772692122/AnsiballZ_docker_container.py\", line 92, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/azureuser/.ansible/tmp/ansible-tmp-1627168524.2112486-419-271310772692122/AnsiballZ_docker_container.py\", line 41, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib/python3.6/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.6/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_docker_container_payload_cz90wkde/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 3619, in <module>\r\n  File \"/tmp/ansible_docker_container_payload_cz90wkde/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 3608, in main\r\n  File \"/tmp/ansible_docker_container_payload_cz90wkde/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 2754, in __init__\r\n  File \"/tmp/ansible_docker_container_payload_cz90wkde/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1422, in __init__\r\n  File \"/tmp/ansible_docker_container_payload_cz90wkde/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1789, in _parse_publish_ports\r\nUnboundLocalError: local variable 'port_binds' referenced before assignment\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *****************************************************************************************************************************************************************
10.1.0.4                   : ok=5    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

root@736da561d420:/etc/ansible# nano elk_red.yml
root@736da561d420:/etc/ansible# ansible-playbook elk_red.yml
[WARNING]: ansible.utils.display.initialize_locale has not been called, this may result in incorrectly calculated text widths that can cause Display to print incorrect
line lengths

PLAY [Config elk vm with Docker] *******************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [Use more memory] *****************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [docker.io] ***********************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [Install pip3] ********************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [Install Docker python module] ****************************************************************************************************************************************
ok: [10.1.0.4]

TASK [download and launch a docker elk container] **************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: UnboundLocalError: local variable 'port_binds' referenced before assignment
fatal: [10.1.0.4]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 10.1.0.4 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/azureuser/.ansible/tmp/ansible-tmp-1627168559.3591685-480-70306973730893/AnsiballZ_docker_container.py\", line 100, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/azureuser/.ansible/tmp/ansible-tmp-1627168559.3591685-480-70306973730893/AnsiballZ_docker_container.py\", line 92, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/azureuser/.ansible/tmp/ansible-tmp-1627168559.3591685-480-70306973730893/AnsiballZ_docker_container.py\", line 41, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib/python3.6/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.6/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_docker_container_payload_nmmmuqqy/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 3619, in <module>\r\n  File \"/tmp/ansible_docker_container_payload_nmmmuqqy/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 3608, in main\r\n  File \"/tmp/ansible_docker_container_payload_nmmmuqqy/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 2754, in __init__\r\n  File \"/tmp/ansible_docker_container_payload_nmmmuqqy/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1422, in __init__\r\n  File \"/tmp/ansible_docker_container_payload_nmmmuqqy/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1789, in _parse_publish_ports\r\nUnboundLocalError: local variable 'port_binds' referenced before assignment\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *****************************************************************************************************************************************************************
10.1.0.4                   : ok=5    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

root@736da561d420:/etc/ansible# sudo docker ps
bash: sudo: command not found
root@736da561d420:/etc/ansible# nano elk_red.yml
root@736da561d420:/etc/ansible# sudo docker ps
bash: sudo: command not found
root@736da561d420:/etc/ansible# ansible-playbook elk_red.yml
[WARNING]: ansible.utils.display.initialize_locale has not been called, this may result in incorrectly calculated text widths that can cause Display to print incorrect
line lengths

PLAY [Config elk vm with Docker] *******************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [Use more memory] *****************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [docker.io] ***********************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [Install pip3] ********************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [Install Docker python module] ****************************************************************************************************************************************
ok: [10.1.0.4]

TASK [download and launch a docker elk container] **************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: UnboundLocalError: local variable 'port_binds' referenced before assignment
fatal: [10.1.0.4]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 10.1.0.4 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/azureuser/.ansible/tmp/ansible-tmp-1627168770.8420734-546-83048907810117/AnsiballZ_docker_container.py\", line 100, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/azureuser/.ansible/tmp/ansible-tmp-1627168770.8420734-546-83048907810117/AnsiballZ_docker_container.py\", line 92, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/azureuser/.ansible/tmp/ansible-tmp-1627168770.8420734-546-83048907810117/AnsiballZ_docker_container.py\", line 41, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib/python3.6/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.6/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_docker_container_payload_zy1abpow/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 3619, in <module>\r\n  File \"/tmp/ansible_docker_container_payload_zy1abpow/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 3608, in main\r\n  File \"/tmp/ansible_docker_container_payload_zy1abpow/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 2754, in __init__\r\n  File \"/tmp/ansible_docker_container_payload_zy1abpow/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1422, in __init__\r\n  File \"/tmp/ansible_docker_container_payload_zy1abpow/ansible_docker_container_payload.zip/ansible_collections/community/docker/plugins/modules/docker_container.py\", line 1789, in _parse_publish_ports\r\nUnboundLocalError: local variable 'port_binds' referenced before assignment\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *****************************************************************************************************************************************************************
10.1.0.4                   : ok=5    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

root@736da561d420:/etc/ansible# nano elk_red.yml
root@736da561d420:/etc/ansible# ansible-playbook elk_red.yml
ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  did not find expected '-' indicator

The error appears to be in '/etc/ansible/elk_red.yml': line 31, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

     - name: download and launch a docker elk container
      docker_container:
      ^ here
root@736da561d420:/etc/ansible# nano elk_red.yml
root@736da561d420:/etc/ansible# ansible-playbook elk_red.yml
ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  did not find expected '-' indicator

The error appears to be in '/etc/ansible/elk_red.yml': line 40, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


      - name: Enable service docker on boot
      ^ here
root@736da561d420:/etc/ansible# nano elk_red.yml
root@736da561d420:/etc/ansible# ansible-playbook elk_red.yml
ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to be in '/etc/ansible/elk_red.yml': line 42, column 16, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

     - name: Enable service docker on boot
        systemd:
               ^ here
root@736da561d420:/etc/ansible# nano elk_red.yml
root@736da561d420:/etc/ansible# ansible-playbook elk_red.yml
ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 2 column 1 (char 1)

Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to be in '/etc/ansible/elk_red.yml': line 42, column 16, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

     - name: Enable service docker on boot
        systemd:
               ^ here
root@736da561d420:/etc/ansible# nano elk_red.yml
root@736da561d420:/etc/ansible# ansible-playbook elk_red.yml
[WARNING]: ansible.utils.display.initialize_locale has not been called, this may result in incorrectly calculated text widths that can cause Display to print incorrect
line lengths

PLAY [Config elk vm with Docker] *******************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [Use more memory] *****************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [docker.io] ***********************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [Install pip3] ********************************************************************************************************************************************************
ok: [10.1.0.4]

TASK [Install Docker python module] ****************************************************************************************************************************************
ok: [10.1.0.4]

TASK [download and launch a docker elk container] **************************************************************************************************************************
[DEPRECATION WARNING]: The container_default_behavior option will change its default value from "compatibility" to "no_defaults" in community.docker 2.0.0. To remove this
warning, please specify an explicit value for it now. This feature will be removed from community.docker in version 2.0.0. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
changed: [10.1.0.4]

PLAY RECAP *****************************************************************************************************************************************************************
10.1.0.4                   : ok=6    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

root@736da561d420:/etc/ansible# sudo
bash: sudo: command not found
root@736da561d420:/etc/ansible# ~
bash: /root: Is a directory
root@736da561d420:/etc/ansible# cd
root@736da561d420:~# ssh azureuser@40.78.109.238
Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1055-azure x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

 System information disabled due to load higher than 2.0

 * Super-optimized for small spaces - read how we shrank the memory
   footprint of MicroK8s to make it the smallest full K8s around.

   https://ubuntu.com/blog/microk8s-memory-optimisation

10 updates can be applied immediately.
10 of these updates are standard security updates.
To see these additional updates run: apt list --upgradable

New release '20.04.2 LTS' available.
Run 'do-release-upgrade' to upgrade to it.


Last login: Sat Jul 24 23:28:52 2021 from 10.0.0.4
azureuser@ELK-SERVER:~$ sudo docker ps
CONTAINER ID   IMAGE          COMMAND                  CREATED         STATUS         PORTS                                                                              NAMES
0937779ec13c   sebp/elk:761   "/usr/local/bin/star…"   2 minutes ago   Up 2 minutes   0.0.0.0:5044->5044/tcp, 0.0.0.0:5601->5601/tcp, 0.0.0.0:9200->9200/tcp, 9300/tcp   elk
azureuser@ELK-SERVER:~$ sudo
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user] [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p prompt] [-T timeout] [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p prompt] [-T timeout] [-u user] file ...
azureuser@ELK-SERVER:~$ sudo su
root@ELK-SERVER:/home/azureuser# cd ~
root@ELK-SERVER:~# ls
root@ELK-SERVER:~# ping
Usage: ping [-aAbBdDfhLnOqrRUvV64] [-c count] [-i interval] [-I interface]
            [-m mark] [-M pmtudisc_option] [-l preload] [-p pattern] [-Q tos]
            [-s packetsize] [-S sndbuf] [-t ttl] [-T timestamp_option]
            [-w deadline] [-W timeout] [hop1 ...] destination
Usage: ping -6 [-aAbBdDfhLnOqrRUvV] [-c count] [-i interval] [-I interface]
             [-l preload] [-m mark] [-M pmtudisc_option]
             [-N nodeinfo_option] [-p pattern] [-Q tclass] [-s packetsize]
             [-S sndbuf] [-t ttl] [-T timestamp_option] [-w deadline]
             [-W timeout] destination
root@ELK-SERVER:~# nmap -p 80

Command 'nmap' not found, but can be installed with:

snap install nmap  # version 7.91, or
apt  install nmap

See 'snap info nmap' for additional versions.

root@ELK-SERVER:~# cd ~/
root@ELK-SERVER:~# ls
root@ELK-SERVER:~# ping 40.78.109.238
PING 40.78.109.238 (40.78.109.238) 56(84) bytes of data.
^[[A^[[A^[[B^[[B^[[B
^X
^Z
[1]+  Stopped                 ping 40.78.109.238
root@ELK-SERVER:~# docker container list -a
CONTAINER ID   IMAGE          COMMAND                  CREATED          STATUS          PORTS                                                                              NAMES
0937779ec13c   sebp/elk:761   "/usr/local/bin/star…"   34 minutes ago   Up 34 minutes   0.0.0.0:5044->5044/tcp, 0.0.0.0:5601->5601/tcp, 0.0.0.0:9200->9200/tcp, 9300/tcp   elk
root@ELK-SERVER:~# docker stark elk
docker: 'stark' is not a docker command.
See 'docker --help'
root@ELK-SERVER:~# ls
root@ELK-SERVER:~# cd  ~../
bash: cd: ~../: No such file or directory
root@ELK-SERVER:~# cd ~
root@ELK-SERVER:~# ls
root@ELK-SERVER:~# sudo su
root@ELK-SERVER:~# sudo cd ~
sudo: cd: command not found
root@ELK-SERVER:~# ls
root@ELK-SERVER:~# curl https://gist.githubusercontent.com/slape/5cc350109583af6cbe577bbcc0710c93/raw/eca603b72586fbe148c11f9c87bf96a63cb25760/Filebeat >> /etc/ansible/filebeat-config.yml
bash: /etc/ansible/filebeat-config.yml: No such file or directory
root@ELK-SERVER:~# exit
exit
root@ELK-SERVER:~# exit
exit
There are stopped jobs.
root@ELK-SERVER:~# cd exit
bash: cd: exit: No such file or directory
root@ELK-SERVER:~# exit
exit
There are stopped jobs.
root@ELK-SERVER:~# curl https://gist.githubusercontent.com/slape/5cc350109583af6cbe577bbcc0710c93/raw/eca603b72586fbe148c11f9c87bf96a63cb25760/Filebeat >> /etc/ansible/filebeat-config.yml
bash: /etc/ansible/filebeat-config.yml: No such file or directory
root@ELK-SERVER:~# sudo su
root@ELK-SERVER:~# sudo docker ps
CONTAINER ID   IMAGE          COMMAND                  CREATED             STATUS             PORTS                                                                              NAMES
0937779ec13c   sebp/elk:761   "/usr/local/bin/star…"   About an hour ago   Up About an hour   0.0.0.0:5044->5044/tcp, 0.0.0.0:5601->5601/tcp, 0.0.0.0:9200->9200/tcp, 9300/tcp   elk
root@ELK-SERVER:~# ls
root@ELK-SERVER:~# sudo elk
sudo: elk: command not found
root@ELK-SERVER:~# sudo cd elk
sudo: cd: command not found
root@ELK-SERVER:~# cd elk
bash: cd: elk: No such file or directory
root@ELK-SERVER:~# docker container list -s
CONTAINER ID   IMAGE          COMMAND                  CREATED             STATUS             PORTS                                                                              NAMES     SIZE
0937779ec13c   sebp/elk:761   "/usr/local/bin/star…"   About an hour ago   Up About an hour   0.0.0.0:5044->5044/tcp, 0.0.0.0:5601->5601/tcp, 0.0.0.0:9200->9200/tcp, 9300/tcp   elk       135MB (virtual 2.2GB)
root@ELK-SERVER:~# docker container list -a
CONTAINER ID   IMAGE          COMMAND                  CREATED             STATUS             PORTS                                                                              NAMES
0937779ec13c   sebp/elk:761   "/usr/local/bin/star…"   About an hour ago   Up About an hour   0.0.0.0:5044->5044/tcp, 0.0.0.0:5601->5601/tcp, 0.0.0.0:9200->9200/tcp, 9300/tcp   elk
root@ELK-SERVER:~# docker stark elk
docker: 'stark' is not a docker command.
See 'docker --help'
root@ELK-SERVER:~# docker stop elk
elk
root@ELK-SERVER:~# docker container list -a
CONTAINER ID   IMAGE          COMMAND                  CREATED             STATUS                      PORTS     NAMES
0937779ec13c   sebp/elk:761   "/usr/local/bin/star…"   About an hour ago   Exited (0) 15 seconds ago             elk
root@ELK-SERVER:~# /etc/ansible
bash: /etc/ansible: No such file or directory
root@ELK-SERVER:~# cd /etc/ansible
bash: cd: /etc/ansible: No such file or directory
root@ELK-SERVER:~# ls
root@ELK-SERVER:~# exit
exit
root@ELK-SERVER:~# ls
root@ELK-SERVER:~# ansible-playbook.yml
ansible-playbook.yml: command not found
root@ELK-SERVER:~# curl https://gist.githubusercontent.com/slape/5cc350109583af6cbe577bbcc0710c93/raw/eca603b72586fbe148c11f9c87bf96a63cb25760/Filebeat > /etc/ansible/files/filebeat-config.yml
bash: /etc/ansible/files/filebeat-config.yml: No such file or directory
root@ELK-SERVER:~# git clone
fatal: You must specify a repository to clone.

usage: git clone [<options>] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
    --progress            force progress reporting
    -n, --no-checkout     don't create a checkout
    --bare                create a bare repository
    --mirror              create a mirror repository (implies bare)
    -l, --local           to clone from a local repository
    --no-hardlinks        don't use local hardlinks, always copy
    -s, --shared          setup as shared repository
    --recurse-submodules[=<pathspec>]
                          initialize submodules in the clone
    -j, --jobs <n>        number of submodules cloned in parallel
    --template <template-directory>
                          directory from which templates will be used
    --reference <repo>    reference repository
    --reference-if-able <repo>
                          reference repository
    --dissociate          use --reference only while cloning
    -o, --origin <name>   use <name> instead of 'origin' to track upstream
    -b, --branch <branch>
                          checkout <branch> instead of the remote's HEAD
    -u, --upload-pack <path>
                          path to git-upload-pack on the remote
    --depth <depth>       create a shallow clone of that depth
    --shallow-since <time>
                          create a shallow clone since a specific time
    --shallow-exclude <revision>
                          deepen history of shallow clone, excluding rev
    --single-branch       clone only one branch, HEAD or --branch
    --no-tags             don't clone any tags, and make later fetches not to follow them
    --shallow-submodules  any cloned submodules will be shallow
    --separate-git-dir <gitdir>
                          separate git dir from working tree
    -c, --config <key=value>
                          set config inside the new repository
    -4, --ipv4            use IPv4 addresses only
    -6, --ipv6            use IPv6 addresses only
    --filter <args>       object filtering

root@ELK-SERVER:~# git clone https://github.com/pt2493/project-1.git
Cloning into 'project-1'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
root@ELK-SERVER:~# exit
There are stopped jobs.
root@ELK-SERVER:~# exit
azureuser@ELK-SERVER:~$ logout
Connection to 40.78.109.238 closed.
root@736da561d420:~# git clone https://github.com/pt2493/project-1.git
bash: git: command not found
root@736da561d420:~# sudo get clone https://github.com/pt2493/project-1.git
bash: sudo: command not found
root@736da561d420:~#
